// import type { Wine } from "../../models/wines";

// const wines: Wine[] = [
//   {
//     name: "Château Margaux",
//     year: 2015,
//     country: "France",
//     region: "Bordeaux",
//     grape: "Cabernet Sauvignon",
//     kind: "Red",
//     boughtAt: new Date("2020-01-01"),
//     quantity: 6,
//     quantityLeft: 4,
//   },
//   {
//     name: "Sassicaia",
//     year: 2016,
//     country: "Italy",
//     region: "Tuscany",
//     grape: "Cabernet Sauvignon",
//     kind: "Red",
//     boughtAt: new Date("2004-01-05"),
//     quantity: 3,
//     quantityLeft: 0,
//   },
//   {
//     name: "Penfolds Grange",
//     year: 2014,
//     country: "Australia",
//     region: "South Australia",
//     grape: "Shiraz",
//     kind: "Red",
//     boughtAt: new Date("2020-01-01"),
//     quantity: 2,
//     quantityLeft: 1,
//   },
//   {
//     name: "Cloudy Bay Sauvignon Blanc",
//     year: 2020,
//     country: "New Zealand",
//     region: "Marlborough",
//     grape: "Sauvignon Blanc",
//     kind: "White",
//     boughtAt: new Date("2025-01-01"),
//     quantity: 5,
//     quantityLeft: 5,
//   },
//   {
//     name: "Dom Pérignon",
//     year: 2012,
//     country: "France",
//     region: "Champagne",
//     grape: "Chardonnay, Pinot Noir",
//     kind: "Sparkling",
//     boughtAt: new Date("2023-01-01"),
//     quantity: 4,
//     quantityLeft: 2,
//   },
//   {
//     name: "Opus One",
//     year: 2018,
//     country: "USA",
//     region: "Napa Valley",
//     grape: "Cabernet Sauvignon",
//     kind: "Red",
//     boughtAt: new Date("2022-06-15"),
//     quantity: 2,
//     quantityLeft: 2,
//   },
//   {
//     name: "Barolo Brunate",
//     year: 2017,
//     country: "Italy",
//     region: "Piedmont",
//     grape: "Nebbiolo",
//     kind: "Red",
//     boughtAt: new Date("2021-09-10"),
//     quantity: 6,
//     quantityLeft: 3,
//   },
//   {
//     name: "Chablis Grand Cru",
//     year: 2019,
//     country: "France",
//     region: "Burgundy",
//     grape: "Chardonnay",
//     kind: "White",
//     boughtAt: new Date("2022-03-20"),
//     quantity: 4,
//     quantityLeft: 4,
//   },
//   {
//     name: "Screaming Eagle",
//     year: 2016,
//     country: "USA",
//     region: "Napa Valley",
//     grape: "Cabernet Sauvignon",
//     kind: "Red",
//     boughtAt: new Date("2020-11-05"),
//     quantity: 1,
//     quantityLeft: 0,
//   },
//   {
//     name: "Riesling Spätlese",
//     year: 2020,
//     country: "Germany",
//     region: "Mosel",
//     grape: "Riesling",
//     kind: "White",
//     boughtAt: new Date("2021-04-12"),
//     quantity: 8,
//     quantityLeft: 6,
//   },
//   {
//     name: "Caymus Cabernet",
//     year: 2019,
//     country: "USA",
//     region: "Napa Valley",
//     grape: "Cabernet Sauvignon",
//     kind: "Red",
//     boughtAt: new Date("2022-08-30"),
//     quantity: 12,
//     quantityLeft: 8,
//   },
//   {
//     name: "Pol Roger Champagne",
//     year: 2014,
//     country: "France",
//     region: "Champagne",
//     grape: "Chardonnay, Pinot Noir",
//     kind: "Sparkling",
//     boughtAt: new Date("2019-12-24"),
//     quantity: 6,
//     quantityLeft: 1,
//   },
//   {
//     name: "Amarone della Valpolicella",
//     year: 2015,
//     country: "Italy",
//     region: "Veneto",
//     grape: "Corvina, Rondinella",
//     kind: "Red",
//     boughtAt: new Date("2020-05-18"),
//     quantity: 3,
//     quantityLeft: 2,
//   },
//   {
//     name: "Sancerre",
//     year: 2021,
//     country: "France",
//     region: "Loire Valley",
//     grape: "Sauvignon Blanc",
//     kind: "White",
//     boughtAt: new Date("2022-07-08"),
//     quantity: 6,
//     quantityLeft: 5,
//   },
//   {
//     name: "Château d'Yquem",
//     year: 2010,
//     country: "France",
//     region: "Bordeaux",
//     grape: "Sémillon, Sauvignon Blanc",
//     kind: "White",
//     boughtAt: new Date("2018-10-15"),
//     quantity: 2,
//     quantityLeft: 1,
//   },
//   {
//     name: "Rioja Gran Reserva",
//     year: 2013,
//     country: "Spain",
//     region: "Rioja",
//     grape: "Tempranillo",
//     kind: "Red",
//     boughtAt: new Date("2021-02-28"),
//     quantity: 6,
//     quantityLeft: 4,
//   },
//   {
//     name: "Pinot Noir Willamette",
//     year: 2020,
//     country: "USA",
//     region: "Oregon",
//     grape: "Pinot Noir",
//     kind: "Red",
//     boughtAt: new Date("2023-04-10"),
//     quantity: 4,
//     quantityLeft: 3,
//   },
//   {
//     name: "Gevrey-Chambertin",
//     year: 2018,
//     country: "France",
//     region: "Burgundy",
//     grape: "Pinot Noir",
//     kind: "Red",
//     boughtAt: new Date("2022-11-20"),
//     quantity: 3,
//     quantityLeft: 2,
//   },
//   {
//     name: "Grüner Veltliner",
//     year: 2021,
//     country: "Austria",
//     region: "Wachau",
//     grape: "Grüner Veltliner",
//     kind: "White",
//     boughtAt: new Date("2023-05-15"),
//     quantity: 6,
//     quantityLeft: 6,
//   },
//   {
//     name: "Côtes du Rhône Villages",
//     year: 2017,
//     country: "France",
//     region: "Rhône Valley",
//     grape: "Grenache, Syrah",
//     kind: "Red",
//     boughtAt: new Date("2020-09-12"),
//     quantity: 12,
//     quantityLeft: 7,
//   },
//   {
//     name: "Chianti Classico Riserva",
//     year: 2016,
//     country: "Italy",
//     region: "Tuscany",
//     grape: "Sangiovese",
//     kind: "Red",
//     boughtAt: new Date("2021-06-05"),
//     quantity: 8,
//     quantityLeft: 5,
//   },
//   {
//     name: "Albariño",
//     year: 2022,
//     country: "Spain",
//     region: "Rías Baixas",
//     grape: "Albariño",
//     kind: "White",
//     boughtAt: new Date("2023-08-20"),
//     quantity: 6,
//     quantityLeft: 6,
//   },
//   {
//     name: "Hermitage Rouge",
//     year: 2015,
//     country: "France",
//     region: "Rhône Valley",
//     grape: "Syrah",
//     kind: "Red",
//     boughtAt: new Date("2019-03-10"),
//     quantity: 2,
//     quantityLeft: 0,
//   },
//   {
//     name: "Prosecco di Valdobbiadene",
//     year: 2022,
//     country: "Italy",
//     region: "Veneto",
//     grape: "Glera",
//     kind: "Sparkling",
//     boughtAt: new Date("2023-01-15"),
//     quantity: 12,
//     quantityLeft: 9,
//   },
//   {
//     name: "Châteauneuf-du-Pape",
//     year: 2014,
//     country: "France",
//     region: "Rhône Valley",
//     grape: "Grenache, Syrah, Mourvèdre",
//     kind: "Red",
//     boughtAt: new Date("2018-11-25"),
//     quantity: 4,
//     quantityLeft: 1,
//   },
//   {
//     name: "Montrachet",
//     year: 2017,
//     country: "France",
//     region: "Burgundy",
//     grape: "Chardonnay",
//     kind: "White",
//     boughtAt: new Date("2021-12-03"),
//     quantity: 1,
//     quantityLeft: 1,
//   },
//   {
//     name: "Toro Tinta de Toro",
//     year: 2018,
//     country: "Spain",
//     region: "Toro",
//     grape: "Tinta de Toro",
//     kind: "Red",
//     boughtAt: new Date("2022-04-18"),
//     quantity: 6,
//     quantityLeft: 4,
//   },
//   {
//     name: "Barossa Valley Shiraz",
//     year: 2019,
//     country: "Australia",
//     region: "Barossa Valley",
//     grape: "Shiraz",
//     kind: "Red",
//     boughtAt: new Date("2023-02-14"),
//     quantity: 6,
//     quantityLeft: 5,
//   },
//   {
//     name: "Vouvray Demi-Sec",
//     year: 2020,
//     country: "France",
//     region: "Loire Valley",
//     grape: "Chenin Blanc",
//     kind: "White",
//     boughtAt: new Date("2022-09-07"),
//     quantity: 4,
//     quantityLeft: 3,
//   },
//   {
//     name: "Cava Brut Nature",
//     year: 2019,
//     country: "Spain",
//     region: "Penedès",
//     grape: "Xarel·lo, Macabeo, Parellada",
//     kind: "Sparkling",
//     boughtAt: new Date("2021-07-22"),
//     quantity: 12,
//     quantityLeft: 8,
//   },
//   {
//     name: "Brunello di Montalcino",
//     year: 2016,
//     country: "Italy",
//     region: "Tuscany",
//     grape: "Sangiovese",
//     kind: "Red",
//     boughtAt: new Date("2020-12-10"),
//     quantity: 3,
//     quantityLeft: 2,
//   },
//   {
//     name: "Muscadet Sèvre-et-Maine",
//     year: 2021,
//     country: "France",
//     region: "Loire Valley",
//     grape: "Melon de Bourgogne",
//     kind: "White",
//     boughtAt: new Date("2022-05-30"),
//     quantity: 6,
//     quantityLeft: 4,
//   },
//   {
//     name: "Vintage Port",
//     year: 2011,
//     country: "Portugal",
//     region: "Douro",
//     grape: "Touriga Nacional, Tinta Roriz",
//     kind: "Red",
//     boughtAt: new Date("2017-08-15"),
//     quantity: 6,
//     quantityLeft: 4,
//   },
//   {
//     name: "Gewürztraminer",
//     year: 2020,
//     country: "Germany",
//     region: "Alsace",
//     grape: "Gewürztraminer",
//     kind: "White",
//     boughtAt: new Date("2021-10-12"),
//     quantity: 4,
//     quantityLeft: 2,
//   },
//   {
//     name: "Malbec Mendoza",
//     year: 2019,
//     country: "Argentina",
//     region: "Mendoza",
//     grape: "Malbec",
//     kind: "Red",
//     boughtAt: new Date("2022-01-08"),
//     quantity: 12,
//     quantityLeft: 10,
//   },
//   {
//     name: "Vinho Verde",
//     year: 2022,
//     country: "Portugal",
//     region: "Minho",
//     grape: "Loureiro, Arinto",
//     kind: "White",
//     boughtAt: new Date("2023-06-25"),
//     quantity: 8,
//     quantityLeft: 7,
//   },
//   {
//     name: "Carménère Reserve",
//     year: 2020,
//     country: "Chile",
//     region: "Colchagua Valley",
//     grape: "Carménère",
//     kind: "Red",
//     boughtAt: new Date("2023-03-15"),
//     quantity: 6,
//     quantityLeft: 5,
//   },
//   {
//     name: "Tokaj Aszú 5 Puttonyos",
//     year: 2013,
//     country: "Hungary",
//     region: "Tokaj",
//     grape: "Furmint, Hárslevelű",
//     kind: "White",
//     boughtAt: new Date("2019-04-20"),
//     quantity: 3,
//     quantityLeft: 2,
//   },
//   {
//     name: "Côte-Rôtie",
//     year: 2016,
//     country: "France",
//     region: "Rhône Valley",
//     grape: "Syrah",
//     kind: "Red",
//     boughtAt: new Date("2020-07-11"),
//     quantity: 2,
//     quantityLeft: 1,
//   },
//   {
//     name: "Marlborough Pinot Noir",
//     year: 2021,
//     country: "New Zealand",
//     region: "Marlborough",
//     grape: "Pinot Noir",
//     kind: "Red",
//     boughtAt: new Date("2023-09-05"),
//     quantity: 4,
//     quantityLeft: 4,
//   },
//   {
//     name: "Franciacorta DOCG",
//     year: 2018,
//     country: "Italy",
//     region: "Lombardy",
//     grape: "Chardonnay, Pinot Nero",
//     kind: "Sparkling",
//     boughtAt: new Date("2021-11-18"),
//     quantity: 6,
//     quantityLeft: 3,
//   },
//   {
//     name: "Pouilly-Fumé",
//     year: 2020,
//     country: "France",
//     region: "Loire Valley",
//     grape: "Sauvignon Blanc",
//     kind: "White",
//     boughtAt: new Date("2022-10-28"),
//     quantity: 4,
//     quantityLeft: 3,
//   },
//   {
//     name: "Etna Rosso",
//     year: 2018,
//     country: "Italy",
//     region: "Sicily",
//     grape: "Nerello Mascalese",
//     kind: "Red",
//     boughtAt: new Date("2021-05-14"),
//     quantity: 6,
//     quantityLeft: 4,
//   },
//   {
//     name: "Condrieu",
//     year: 2019,
//     country: "France",
//     region: "Rhône Valley",
//     grape: "Viognier",
//     kind: "White",
//     boughtAt: new Date("2022-02-09"),
//     quantity: 2,
//     quantityLeft: 1,
//   },
//   {
//     name: "Priorat",
//     year: 2017,
//     country: "Spain",
//     region: "Priorat",
//     grape: "Garnacha, Cariñena",
//     kind: "Red",
//     boughtAt: new Date("2020-08-03"),
//     quantity: 4,
//     quantityLeft: 2,
//   },
//   {
//     name: "Clare Valley Riesling",
//     year: 2021,
//     country: "Australia",
//     region: "Clare Valley",
//     grape: "Riesling",
//     kind: "White",
//     boughtAt: new Date("2023-07-12"),
//     quantity: 6,
//     quantityLeft: 6,
//   },
//   {
//     name: "Bandol Rouge",
//     year: 2015,
//     country: "France",
//     region: "Provence",
//     grape: "Mourvèdre",
//     kind: "Red",
//     boughtAt: new Date("2019-06-08"),
//     quantity: 3,
//     quantityLeft: 1,
//   },
//   {
//     name: "Soave Classico",
//     year: 2021,
//     country: "Italy",
//     region: "Veneto",
//     grape: "Garganega",
//     kind: "White",
//     boughtAt: new Date("2022-12-15"),
//     quantity: 8,
//     quantityLeft: 6,
//   },
//   {
//     name: "Côtes de Provence Rosé",
//     year: 2022,
//     country: "France",
//     region: "Provence",
//     grape: "Grenache, Cinsault",
//     kind: "Rosé",
//     boughtAt: new Date("2023-05-28"),
//     quantity: 12,
//     quantityLeft: 10,
//   },
//   {
//     name: "Valpolicella Ripasso",
//     year: 2019,
//     country: "Italy",
//     region: "Veneto",
//     grape: "Corvina, Rondinella",
//     kind: "Red",
//     boughtAt: new Date("2022-03-04"),
//     quantity: 6,
//     quantityLeft: 3,
//   },
// ];

// export default wines;
